
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import mqttSender
import tkinter
import tkinter.scrolledtext

user_id=""                      # your mqtt account name         
user_pwd=""                     # your mqtt account password                                      
mqtt_server=""                  # your mqtt IP address or domain         
mqtt_clientID=""                # your unique client id         
mqtt_topic=""                   # the topic you want to send message

def button_1_set():

    global user_id                 # your mqtt account password                                      
    global mqtt_topic              # your mqtt IP address or domain         
    global mqtt_clientID          # your unique client id         
    global user_pwd
    global message
    global mqtt_server
    print("button_1_set()")
    user_id =entry_2.get()                     # your mqtt account password                                      
    mqtt_topic=entry_3.get()                  # your mqtt IP address or domain         
    mqtt_clientID=entry_4.get()                # your unique client id         
    user_pwd=entry_5.get()
    message=entry_6.get()
    mqtt_server=entry_7.get()
    mqtt=mqttSender.MqttSender(user_id=user_id,user_pwd=user_pwd,client_id=mqtt_clientID,mqtt_server=mqtt_server)
    print(user_id)
    print(mqtt_topic)
    print(mqtt_clientID)
    print(user_pwd)
    print(message)
    print(mqtt_server)

def button_2_send():
    global user_id                 # your mqtt account password                                      
    global mqtt_topic              # your mqtt IP address or domain         
    global mqtt_clientID          # your unique client id         
    global user_pwd
    global message
    global mqtt_server
    print("button_2_send()")
    print(user_id)
    print(mqtt_topic)
    print(mqtt_clientID)
    print(user_pwd)
    print(message)
    print(mqtt_server)
    message=entry_6.get()
    mqtt_topic=entry_3.get()   
    mqtt=mqttSender.MqttSender(user_id=user_id,user_pwd=user_pwd,client_id=mqtt_clientID,mqtt_server=mqtt_server)
    mqtt.sendMessage(mqtt_topic,message)
    message="message : "+message+"\n"
    entry_1.insert("end",message)


# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"H:\git_project\MqttSender\MqttSender\src\GUI\gui_ver_2\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("816x557")
window.configure(bg = "#381F9D")


canvas = Canvas(
    window,
    bg = "#381F9D",
    height = 557,
    width = 816,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    408.0,
    400.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=22.0,
    y=289.0,
    width=772.0,
    height=220.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    222.0,
    62.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FAFAFA",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=149.0,
    y=43.0,
    width=146.0,
    height=36.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    616.0,
    58.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FAFAFA",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=492.0,
    y=39.0,
    width=248.0,
    height=36.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    222.0,
    176.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FAFAFA",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=149.0,
    y=157.0,
    width=146.0,
    height=36.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    222.0,
    119.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FAFAFA",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=149.0,
    y=100.0,
    width=146.0,
    height=36.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    616.0,
    119.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FAFAFA",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=492.0,
    y=100.0,
    width=248.0,
    height=36.0
)

canvas.create_text(
    44.0,
    46.0,
    anchor="nw",
    text="USERID:",
    fill="#C2B21F",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    344.0,
    43.0,
    anchor="nw",
    text="TOPIC:",
    fill="#C2B21F",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    13.0,
    103.0,
    anchor="nw",
    text="USERPWD:",
    fill="#C2B21F",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    17.0,
    160.0,
    anchor="nw",
    text="DEVICE ID:",
    fill="#C2B21F",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    23.0,
    0.0,
    anchor="nw",
    text="mqttSender version 2.0",
    fill="#FFFFFF",
    font=("KleeOne Regular", 14 * -1)
)

canvas.create_text(
    344.0,
    99.0,
    anchor="nw",
    text="MESSAGE:\n",
    fill="#C2B21F",
    font=("Inter", 24 * -1)
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    616.0,
    181.0,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#FAFAFA",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=492.0,
    y=162.0,
    width=248.0,
    height=36.0
)

canvas.create_text(
    344.0,
    161.0,
    anchor="nw",
    text="Server:",
    fill="#C2B21F",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    540.0,
    5.0,
    anchor="nw",
    text="Regen mqttSender v2.0",
    fill="#FFFFFF",
    font=("Inter Italic", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=button_1_set,
    relief="flat"
)
button_1.place(
    x=111.0,
    y=229.0,
    width=184.0,
    height=40.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=button_2_send,
    relief="flat"
)
button_2.place(
    x=492.0,
    y=230.0,
    width=253.0,
    height=40.0
)
window.resizable(False, False)
window.mainloop()
